Se agregó en el footer las redes sociales.
jess-jurado/Craftiness pull request #3
Opened 2021-02-10 11:52 UTC by jess-jurado

Hola Daniel este es el primer pull request 😜

2021-02-10 12:26 UTC, danimm commented on proyecto.html
> +            <h3>Suscribete a redes sociales</h3>
Yo cambiaría el contenido mejor por: "Subscríbete a nuestras redes sociales"

2021-02-10 12:30 UTC, danimm commented on css/estilos.css
> +    .footer{
Como standard se deja un espaciado entre el selector y las llaves:
```sass
.footer {
  // properties..
}
```

2021-02-10 12:32 UTC, danimm requested changes
Cuando hagas esos cambios, vuelve a hacer un push de tu rama Footer.
Solo entonces aprobaré el PR (Pull Request)....si eso...🙃

2021-02-11 11:38 UTC, jess-jurado commented
Hola Daniel, ya hice los cambios que requerías, por favor compruebalos y haz el merge. 😉

2021-02-11 12:40 UTC, danimm approved these changes
Perfecto, confirmo el PR.

2021-02-11 12:41 UTC, merged

2021-02-11 12:43 UTC, danimm commented
@jess-jurado No olvides actualizar tu rama master en local haciendo un pull para traer estos nuevos cambios 👍🏻